### ISSUE TITLE
Keep getting a HUGE error on "TASK [php : Install PHP 7.0]"

### ISSUE THREAD

**Issue by reverbsoul** [roots/trellis#540]
## My environment

OS: 10.10.5
Python Version: 2.7.10
Ansible Version: 2.0.1.0

## Here's what I tried

vagrant up

## What I got

The following error message occurs:

```
failed: [default] => (item=[u'php7.0-cli', u'php7.0-common', u'php7.0-curl', u'php7.0-dev', u'php7.0-fpm', u'php7.0-gd', u'php7.0-mbstring', u'php7.0-mcrypt', u'php7.0-mysql', u'php7.0-opcache', u'php7.0-xml', u'php7.0-xmlrpc', u'php7.0-zip']) => {"cache_update_time": 0, "cache_updated": false, "failed": true, "item": ["php7.0-cli", "php7.0-common", "php7.0-curl", "php7.0-dev", "php7.0-fpm", "php7.0-gd", "php7.0-mbstring", "php7.0-mcrypt", "php7.0-mysql", "php7.0-opcache", "php7.0-xml", "php7.0-xmlrpc", "php7.0-zip"], "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\" --force-yes  install 'php7.0-cli' 'php7.0-common' 'php7.0-curl' 'php7.0-dev' 'php7.0-fpm' 'php7.0-gd' 'php7.0-mbstring' 'php7.0-mcrypt' 'php7.0-mysql' 'php7.0-opcache' 'php7.0-xml' 'php7.0-xmlrpc' 'php7.0-zip'' failed: \rExtracting templates from packages: 60%\rExtracting templates from packages: 100%\n\nCreating config file /etc/php/7.0/mods-available/calendar.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/ctype.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/exif.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/fileinfo.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/ftp.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/gettext.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/iconv.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/pdo.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/phar.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/posix.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/shmop.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/sockets.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/sysvmsg.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/sysvsem.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/sysvshm.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/tokenizer.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/json.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/opcache.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/readline.ini with new version\nError: The new file /usr/lib/php/7.0/php.ini-production.cli does not exist!\ndpkg: error processing package php7.0-cli (--configure):\n subprocess installed post-installation script returned error exit status 1\n\nCreating config file /etc/php/7.0/mods-available/dom.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/simplexml.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/wddx.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/xml.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/xmlreader.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/xmlwriter.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/xsl.ini with new version\ndpkg: dependency problems prevent configuration of php-pear:\n php-pear depends on php-cli; however:\n  Package php-cli is not installed.\n  Package php7.0-cli which provides php-cli is not configured yet.\n\ndpkg: error processing package php-pear (--configure):\n dependency problems - leaving unconfigured\n\nCreating config file /etc/php/7.0/mods-available/curl.ini with new version\ndpkg: dependency problems prevent configuration of php7.0-dev:\n php7.0-dev depends on php7.0-cli (>= 7.0.5-1+deb.sury.org~trusty+1); however:\n  Package php7.0-cli is not configured yet.\n\ndpkg: error processing package php7.0-dev (--configure):\n dependency problems - leaving unconfigured\ndpkg: dependency problems prevent configuration of php7.0-fpm:\n php7.0-fpm depends on php7.0-cli; however:\n  Package php7.0-cli is not configured yet.\n\ndpkg: error processing package php7.0-fpm (--configure):\n dependency problems - leaving unconfigured\n\nCreating config file /etc/php/7.0/mods-available/gd.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/mbstring.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/mcrypt.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/mysqlnd.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/mysqli.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/pdo_mysql.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/xmlrpc.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/zip.ini with new version\ndpkg: dependency problems prevent configuration of pkg-php-tools:\n pkg-php-tools depends on php-pear; however:\n  Package php-pear is not configured yet.\n pkg-php-tools depends on php-cli; however:\n  Package php-cli is not installed.\n  Package php7.0-cli which provides php-cli is not configured yet.\n\ndpkg: error processing package pkg-php-tools (--configure):\n dependency problems - leaving unconfigured\nErrors were encountered while processing:\n php7.0-cli\n php-pear\n php7.0-dev\n php7.0-fpm\n pkg-php-tools\nE: Sub-process /usr/bin/dpkg returned an error code (1)\n", "stderr": "\rExtracting templates from packages: 60%\rExtracting templates from packages: 100%\n\nCreating config file /etc/php/7.0/mods-available/calendar.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/ctype.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/exif.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/fileinfo.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/ftp.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/gettext.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/iconv.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/pdo.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/phar.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/posix.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/shmop.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/sockets.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/sysvmsg.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/sysvsem.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/sysvshm.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/tokenizer.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/json.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/opcache.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/readline.ini with new version\nError: The new file /usr/lib/php/7.0/php.ini-production.cli does not exist!\ndpkg: error processing package php7.0-cli (--configure):\n subprocess installed post-installation script returned error exit status 1\n\nCreating config file /etc/php/7.0/mods-available/dom.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/simplexml.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/wddx.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/xml.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/xmlreader.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/xmlwriter.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/xsl.ini with new version\ndpkg: dependency problems prevent configuration of php-pear:\n php-pear depends on php-cli; however:\n  Package php-cli is not installed.\n  Package php7.0-cli which provides php-cli is not configured yet.\n\ndpkg: error processing package php-pear (--configure):\n dependency problems - leaving unconfigured\n\nCreating config file /etc/php/7.0/mods-available/curl.ini with new version\ndpkg: dependency problems prevent configuration of php7.0-dev:\n php7.0-dev depends on php7.0-cli (>= 7.0.5-1+deb.sury.org~trusty+1); however:\n  Package php7.0-cli is not configured yet.\n\ndpkg: error processing package php7.0-dev (--configure):\n dependency problems - leaving unconfigured\ndpkg: dependency problems prevent configuration of php7.0-fpm:\n php7.0-fpm depends on php7.0-cli; however:\n  Package php7.0-cli is not configured yet.\n\ndpkg: error processing package php7.0-fpm (--configure):\n dependency problems - leaving unconfigured\n\nCreating config file /etc/php/7.0/mods-available/gd.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/mbstring.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/mcrypt.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/mysqlnd.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/mysqli.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/pdo_mysql.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/xmlrpc.ini with new version\n\nCreating config file /etc/php/7.0/mods-available/zip.ini with new version\ndpkg: dependency problems prevent configuration of pkg-php-tools:\n pkg-php-tools depends on php-pear; however:\n  Package php-pear is not configured yet.\n pkg-php-tools depends on php-cli; however:\n  Package php-cli is not installed.\n  Package php7.0-cli which provides php-cli is not configured yet.\n\ndpkg: error processing package pkg-php-tools (--configure):\n dependency problems - leaving unconfigured\nErrors were encountered while processing:\n php7.0-cli\n php-pear\n php7.0-dev\n php7.0-fpm\n pkg-php-tools\nE: Sub-process /usr/bin/dpkg returned an error code (1)\n", "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following extra packages will be installed:\n  autoconf automake autotools-dev debhelper dh-apparmor dh-php gettext\n  intltool-debian libasprintf-dev libcroco3 libgettextpo-dev libgettextpo0\n  liblist-moreutils-perl libltdl-dev libmail-sendmail-perl libmcrypt4 libpcre3\n  libpcre3-dev libpcrecpp0 libssl-dev libssl-doc libssl1.0.2\n  libsys-hostname-long-perl libtool libunistring0 libxmlrpc-epi0 libxslt1.1\n  libzip4 m4 php-common php-pear php7.0-json php7.0-readline pkg-php-tools\n  po-debconf shtool zlib1g-dev\nSuggested packages:\n  autoconf2.13 autoconf-archive gnu-standards autoconf-doc dh-make\n  apparmor-easyprof gettext-doc libtool-doc libmcrypt-dev mcrypt automaken\n  gfortran fortran95-compiler gcj-jdk libmail-box-perl\nThe following NEW packages will be installed:\n  autoconf automake autotools-dev debhelper dh-apparmor dh-php gettext\n  intltool-debian libasprintf-dev libcroco3 libgettextpo-dev libgettextpo0\n  liblist-moreutils-perl libltdl-dev libmail-sendmail-perl libmcrypt4\n  libpcre3-dev libpcrecpp0 libssl-dev libssl-doc libssl1.0.2\n  libsys-hostname-long-perl libtool libunistring0 libxmlrpc-epi0 libxslt1.1\n  libzip4 m4 php-common php-pear php7.0-cli php7.0-common php7.0-curl\n  php7.0-dev php7.0-fpm php7.0-gd php7.0-json php7.0-mbstring php7.0-mcrypt\n  php7.0-mysql php7.0-opcache php7.0-readline php7.0-xml php7.0-xmlrpc\n  php7.0-zip pkg-php-tools po-debconf shtool zlib1g-dev\nThe following packages will be upgraded:\n  libpcre3\n1 upgraded, 49 newly installed, 0 to remove and 27 not upgraded.\nNeed to get 13.6 MB of archives.\nAfter this operation, 54.3 MB of additional disk space will be used.\nGet:1 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libpcre3 amd64 1:8.31-2ubuntu2.2 [144 kB]\nGet:2 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main libssl1.0.2 amd64 1.0.2g-1+deb.sury.org~trusty+1 [1261 kB]\nGet:3 http://archive.ubuntu.com/ubuntu/ trusty/main libcroco3 amd64 0.6.8-2ubuntu1 [82.4 kB]\nGet:4 http://archive.ubuntu.com/ubuntu/ trusty/main libunistring0 amd64 0.9.3-5ubuntu3 [271 kB]\nGet:5 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libgettextpo0 amd64 0.18.3.1-1ubuntu3 [108 kB]\nGet:6 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libpcrecpp0 amd64 1:8.31-2ubuntu2.2 [14.5 kB]\nGet:7 http://archive.ubuntu.com/ubuntu/ trusty/main libxslt1.1 amd64 1.1.28-2build1 [145 kB]\nGet:8 http://archive.ubuntu.com/ubuntu/ trusty/universe libxmlrpc-epi0 amd64 0.54.2-1ubuntu1 [30.0 kB]\nGet:9 http://archive.ubuntu.com/ubuntu/ trusty/main m4 amd64 1.4.17-2ubuntu1 [195 kB]\nGet:10 http://archive.ubuntu.com/ubuntu/ trusty/main autoconf all 2.69-6 [322 kB]\nGet:11 http://archive.ubuntu.com/ubuntu/ trusty/main autotools-dev all 20130810.1 [44.3 kB]\nGet:12 http://archive.ubuntu.com/ubuntu/ trusty/main automake all 1:1.14.1-2ubuntu1 [510 kB]\nGet:13 http://archive.ubuntu.com/ubuntu/ trusty-updates/main gettext amd64 0.18.3.1-1ubuntu3 [829 kB]\nGet:14 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main libzip4 amd64 1.1.1-1.1+deb.sury.org~trusty+2 [37.7 kB]\nGet:15 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main libssl-dev amd64 1.0.2g-1+deb.sury.org~trusty+1 [1528 kB]\nGet:16 http://archive.ubuntu.com/ubuntu/ trusty/main intltool-debian all 0.35.0+20060710.1 [31.6 kB]\nGet:17 http://archive.ubuntu.com/ubuntu/ trusty/main po-debconf all 1.0.16+nmu2ubuntu1 [210 kB]\nGet:18 http://archive.ubuntu.com/ubuntu/ trusty-updates/main dh-apparmor all 2.8.95~2430-0ubuntu5.3 [12.2 kB]\nGet:19 http://archive.ubuntu.com/ubuntu/ trusty/main debhelper all 9.20131227ubuntu1 [604 kB]\nGet:20 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libasprintf-dev amd64 0.18.3.1-1ubuntu3 [4438 B]\nGet:21 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libgettextpo-dev amd64 0.18.3.1-1ubuntu3 [122 kB]\nGet:22 http://archive.ubuntu.com/ubuntu/ trusty/main liblist-moreutils-perl amd64 0.33-1build3 [48.5 kB]\nGet:23 http://archive.ubuntu.com/ubuntu/ trusty/main libltdl-dev amd64 2.4.2-1.7ubuntu1 [157 kB]\nGet:24 http://archive.ubuntu.com/ubuntu/ trusty/main libsys-hostname-long-perl all 1.4-3 [11.3 kB]\nGet:25 http://archive.ubuntu.com/ubuntu/ trusty/main libmail-sendmail-perl all 0.79.16-1 [26.5 kB]\nGet:26 http://archive.ubuntu.com/ubuntu/ trusty/universe libmcrypt4 amd64 2.5.8-3.1ubuntu1 [61.9 kB]\nGet:27 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libpcre3-dev amd64 1:8.31-2ubuntu2.2 [237 kB]\nGet:28 http://archive.ubuntu.com/ubuntu/ trusty/main zlib1g-dev amd64 1:1.2.8.dfsg-1ubuntu1 [183 kB]\nGet:29 http://archive.ubuntu.com/ubuntu/ trusty/main libtool amd64 2.4.2-1.7ubuntu1 [188 kB]\nGet:30 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main libssl-doc all 1.0.2g-1+deb.sury.org~trusty+1 [1257 kB]\nGet:31 http://archive.ubuntu.com/ubuntu/ trusty/main shtool all 2.0.8-6 [149 kB]\nGet:32 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php-common all 1:36+deb.sury.org~trusty+1 [12.0 kB]\nGet:33 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-common amd64 7.0.5-1+deb.sury.org~trusty+1 [487 kB]\nGet:34 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-json amd64 7.0.5-1+deb.sury.org~trusty+1 [17.0 kB]\nGet:35 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-opcache amd64 7.0.5-1+deb.sury.org~trusty+1 [76.0 kB]\nGet:36 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-readline amd64 7.0.5-1+deb.sury.org~trusty+1 [12.2 kB]\nGet:37 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-cli amd64 7.0.5-1+deb.sury.org~trusty+1 [1248 kB]\nGet:38 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-xml amd64 7.0.5-1+deb.sury.org~trusty+1 [113 kB]\nGet:39 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php-pear all 1:1.10.1+submodules+notgz-6+deb.sury.org~trusty+1 [284 kB]\nGet:40 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-curl amd64 7.0.5-1+deb.sury.org~trusty+1 [26.9 kB]\nGet:41 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-dev amd64 7.0.5-1+deb.sury.org~trusty+1 [508 kB]\nGet:42 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-fpm amd64 7.0.5-1+deb.sury.org~trusty+1 [1254 kB]\nGet:43 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-gd amd64 7.0.5-1+deb.sury.org~trusty+1 [27.0 kB]\nGet:44 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-mbstring amd64 7.0.5-1+deb.sury.org~trusty+1 [462 kB]\nGet:45 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-mcrypt amd64 7.0.5-1+deb.sury.org~trusty+1 [14.5 kB]\nGet:46 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-mysql amd64 7.0.5-1+deb.sury.org~trusty+1 [123 kB]\nGet:47 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-xmlrpc amd64 7.0.5-1+deb.sury.org~trusty+1 [12.8 kB]\nGet:48 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-zip amd64 7.0.5-1+deb.sury.org~trusty+1 [19.9 kB]\nGet:49 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main dh-php all 0.10+deb.sury.org~trusty+1 [7304 B]\nGet:50 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main pkg-php-tools all 1.32+deb.sury.org~trusty+1 [38.1 kB]\nPreconfiguring packages ...\nFetched 13.6 MB in 16s (817 kB/s)\n(Reading database ... 65714 files and directories currently installed.)\nPreparing to unpack .../libpcre3_1%3a8.31-2ubuntu2.2_amd64.deb ...\nUnpacking libpcre3:amd64 (1:8.31-2ubuntu2.2) over (1:8.31-2ubuntu2.1) ...\nProcessing triggers for man-db (2.6.7.1-1ubuntu1) ...\nSetting up libpcre3:amd64 (1:8.31-2ubuntu2.2) ...\nProcessing triggers for libc-bin (2.19-0ubuntu6.7) ...\nSelecting previously unselected package libssl1.0.2:amd64.\n(Reading database ... 65714 files and directories currently installed.)\nPreparing to unpack .../libssl1.0.2_1.0.2g-1+deb.sury.org~trusty+1_amd64.deb ...\nUnpacking libssl1.0.2:amd64 (1.0.2g-1+deb.sury.org~trusty+1) ...\nSelecting previously unselected package libcroco3:amd64.\nPreparing to unpack .../libcroco3_0.6.8-2ubuntu1_amd64.deb ...\nUnpacking libcroco3:amd64 (0.6.8-2ubuntu1) ...\nSelecting previously unselected package libunistring0:amd64.\nPreparing to unpack .../libunistring0_0.9.3-5ubuntu3_amd64.deb ...\nUnpacking libunistring0:amd64 (0.9.3-5ubuntu3) ...\nSelecting previously unselected package libgettextpo0:amd64.\nPreparing to unpack .../libgettextpo0_0.18.3.1-1ubuntu3_amd64.deb ...\nUnpacking libgettextpo0:amd64 (0.18.3.1-1ubuntu3) ...\nSelecting previously unselected package libpcrecpp0:amd64.\nPreparing to unpack .../libpcrecpp0_1%3a8.31-2ubuntu2.2_amd64.deb ...\nUnpacking libpcrecpp0:amd64 (1:8.31-2ubuntu2.2) ...\nSelecting previously unselected package libxslt1.1:amd64.\nPreparing to unpack .../libxslt1.1_1.1.28-2build1_amd64.deb ...\nUnpacking libxslt1.1:amd64 (1.1.28-2build1) ...\nSelecting previously unselected package libzip4:amd64.\nPreparing to unpack .../libzip4_1.1.1-1.1+deb.sury.org~trusty+2_amd64.deb ...\nUnpacking libzip4:amd64 (1.1.1-1.1+deb.sury.org~trusty+2) ...\nSelecting previously unselected package libxmlrpc-epi0:amd64.\nPreparing to unpack .../libxmlrpc-epi0_0.54.2-1ubuntu1_amd64.deb ...\nUnpacking libxmlrpc-epi0:amd64 (0.54.2-1ubuntu1) ...\nSelecting previously unselected package m4.\nPreparing to unpack .../m4_1.4.17-2ubuntu1_amd64.deb ...\nUnpacking m4 (1.4.17-2ubuntu1) ...\nSelecting previously unselected package autoconf.\nPreparing to unpack .../autoconf_2.69-6_all.deb ...\nUnpacking autoconf (2.69-6) ...\nSelecting previously unselected package autotools-dev.\nPreparing to unpack .../autotools-dev_20130810.1_all.deb ...\nUnpacking autotools-dev (20130810.1) ...\nSelecting previously unselected package automake.\nPreparing to unpack .../automake_1%3a1.14.1-2ubuntu1_all.deb ...\nUnpacking automake (1:1.14.1-2ubuntu1) ...\nSelecting previously unselected package gettext.\nPreparing to unpack .../gettext_0.18.3.1-1ubuntu3_amd64.deb ...\nUnpacking gettext (0.18.3.1-1ubuntu3) ...\nSelecting previously unselected package intltool-debian.\nPreparing to unpack .../intltool-debian_0.35.0+20060710.1_all.deb ...\nUnpacking intltool-debian (0.35.0+20060710.1) ...\nSelecting previously unselected package po-debconf.\nPreparing to unpack .../po-debconf_1.0.16+nmu2ubuntu1_all.deb ...\nUnpacking po-debconf (1.0.16+nmu2ubuntu1) ...\nSelecting previously unselected package dh-apparmor.\nPreparing to unpack .../dh-apparmor_2.8.95~2430-0ubuntu5.3_all.deb ...\nUnpacking dh-apparmor (2.8.95~2430-0ubuntu5.3) ...\nSelecting previously unselected package debhelper.\nPreparing to unpack .../debhelper_9.20131227ubuntu1_all.deb ...\nUnpacking debhelper (9.20131227ubuntu1) ...\nSelecting previously unselected package libasprintf-dev:amd64.\nPreparing to unpack .../libasprintf-dev_0.18.3.1-1ubuntu3_amd64.deb ...\nUnpacking libasprintf-dev:amd64 (0.18.3.1-1ubuntu3) ...\nSelecting previously unselected package libgettextpo-dev:amd64.\nPreparing to unpack .../libgettextpo-dev_0.18.3.1-1ubuntu3_amd64.deb ...\nUnpacking libgettextpo-dev:amd64 (0.18.3.1-1ubuntu3) ...\nSelecting previously unselected package liblist-moreutils-perl.\nPreparing to unpack .../liblist-moreutils-perl_0.33-1build3_amd64.deb ...\nUnpacking liblist-moreutils-perl (0.33-1build3) ...\nSelecting previously unselected package libltdl-dev:amd64.\nPreparing to unpack .../libltdl-dev_2.4.2-1.7ubuntu1_amd64.deb ...\nUnpacking libltdl-dev:amd64 (2.4.2-1.7ubuntu1) ...\nSelecting previously unselected package libsys-hostname-long-perl.\nPreparing to unpack .../libsys-hostname-long-perl_1.4-3_all.deb ...\nUnpacking libsys-hostname-long-perl (1.4-3) ...\nSelecting previously unselected package libmail-sendmail-perl.\nPreparing to unpack .../libmail-sendmail-perl_0.79.16-1_all.deb ...\nUnpacking libmail-sendmail-perl (0.79.16-1) ...\nSelecting previously unselected package libmcrypt4.\nPreparing to unpack .../libmcrypt4_2.5.8-3.1ubuntu1_amd64.deb ...\nUnpacking libmcrypt4 (2.5.8-3.1ubuntu1) ...\nSelecting previously unselected package libpcre3-dev:amd64.\nPreparing to unpack .../libpcre3-dev_1%3a8.31-2ubuntu2.2_amd64.deb ...\nUnpacking libpcre3-dev:amd64 (1:8.31-2ubuntu2.2) ...\nSelecting previously unselected package zlib1g-dev:amd64.\nPreparing to unpack .../zlib1g-dev_1%3a1.2.8.dfsg-1ubuntu1_amd64.deb ...\nUnpacking zlib1g-dev:amd64 (1:1.2.8.dfsg-1ubuntu1) ...\nSelecting previously unselected package libssl-dev:amd64.\nPreparing to unpack .../libssl-dev_1.0.2g-1+deb.sury.org~trusty+1_amd64.deb ...\nUnpacking libssl-dev:amd64 (1.0.2g-1+deb.sury.org~trusty+1) ...\nSelecting previously unselected package libssl-doc.\nPreparing to unpack .../libssl-doc_1.0.2g-1+deb.sury.org~trusty+1_all.deb ...\nUnpacking libssl-doc (1.0.2g-1+deb.sury.org~trusty+1) ...\nSelecting previously unselected package libtool.\nPreparing to unpack .../libtool_2.4.2-1.7ubuntu1_amd64.deb ...\nUnpacking libtool (2.4.2-1.7ubuntu1) ...\nSelecting previously unselected package php-common.\nPreparing to unpack .../php-common_1%3a36+deb.sury.org~trusty+1_all.deb ...\nUnpacking php-common (1:36+deb.sury.org~trusty+1) ...\nSelecting previously unselected package php7.0-common.\nPreparing to unpack .../php7.0-common_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...\nUnpacking php7.0-common (7.0.5-1+deb.sury.org~trusty+1) ...\nSelecting previously unselected package php7.0-json.\nPreparing to unpack .../php7.0-json_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...\nUnpacking php7.0-json (7.0.5-1+deb.sury.org~trusty+1) ...\nSelecting previously unselected package php7.0-opcache.\nPreparing to unpack .../php7.0-opcache_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...\nUnpacking php7.0-opcache (7.0.5-1+deb.sury.org~trusty+1) ...\nSelecting previously unselected package php7.0-readline.\nPreparing to unpack .../php7.0-readline_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...\nUnpacking php7.0-readline (7.0.5-1+deb.sury.org~trusty+1) ...\nSelecting previously unselected package php7.0-cli.\nPreparing to unpack .../php7.0-cli_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...\nUnpacking php7.0-cli (7.0.5-1+deb.sury.org~trusty+1) ...\nSelecting previously unselected package php7.0-xml.\nPreparing to unpack .../php7.0-xml_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...\nUnpacking php7.0-xml (7.0.5-1+deb.sury.org~trusty+1) ...\nSelecting previously unselected package php-pear.\nPreparing to unpack .../php-pear_1%3a1.10.1+submodules+notgz-6+deb.sury.org~trusty+1_all.deb ...\nUnpacking php-pear (1:1.10.1+submodules+notgz-6+deb.sury.org~trusty+1) ...\nSelecting previously unselected package php7.0-curl.\nPreparing to unpack .../php7.0-curl_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...\nUnpacking php7.0-curl (7.0.5-1+deb.sury.org~trusty+1) ...\nSelecting previously unselected package shtool.\nPreparing to unpack .../shtool_2.0.8-6_all.deb ...\nUnpacking shtool (2.0.8-6) ...\nSelecting previously unselected package php7.0-dev.\nPreparing to unpack .../php7.0-dev_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...\nUnpacking php7.0-dev (7.0.5-1+deb.sury.org~trusty+1) ...\nSelecting previously unselected package php7.0-fpm.\nPreparing to unpack .../php7.0-fpm_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...\nUnpacking php7.0-fpm (7.0.5-1+deb.sury.org~trusty+1) ...\nSelecting previously unselected package php7.0-gd.\nPreparing to unpack .../php7.0-gd_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...\nUnpacking php7.0-gd (7.0.5-1+deb.sury.org~trusty+1) ...\nSelecting previously unselected package php7.0-mbstring.\nPreparing to unpack .../php7.0-mbstring_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...\nUnpacking php7.0-mbstring (7.0.5-1+deb.sury.org~trusty+1) ...\nSelecting previously unselected package php7.0-mcrypt.\nPreparing to unpack .../php7.0-mcrypt_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...\nUnpacking php7.0-mcrypt (7.0.5-1+deb.sury.org~trusty+1) ...\nSelecting previously unselected package php7.0-mysql.\nPreparing to unpack .../php7.0-mysql_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...\nUnpacking php7.0-mysql (7.0.5-1+deb.sury.org~trusty+1) ...\nSelecting previously unselected package php7.0-xmlrpc.\nPreparing to unpack .../php7.0-xmlrpc_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...\nUnpacking php7.0-xmlrpc (7.0.5-1+deb.sury.org~trusty+1) ...\nSelecting previously unselected package php7.0-zip.\nPreparing to unpack .../php7.0-zip_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...\nUnpacking php7.0-zip (7.0.5-1+deb.sury.org~trusty+1) ...\nSelecting previously unselected package dh-php.\nPreparing to unpack .../dh-php_0.10+deb.sury.org~trusty+1_all.deb ...\nUnpacking dh-php (0.10+deb.sury.org~trusty+1) ...\nSelecting previously unselected package pkg-php-tools.\nPreparing to unpack .../pkg-php-tools_1.32+deb.sury.org~trusty+1_all.deb ...\nUnpacking pkg-php-tools (1.32+deb.sury.org~trusty+1) ...\nProcessing triggers for man-db (2.6.7.1-1ubuntu1) ...\nProcessing triggers for install-info (5.2.0.dfsg.1-2) ...\nProcessing triggers for ureadahead (0.100.0-16) ...\nSetting up libssl1.0.2:amd64 (1.0.2g-1+deb.sury.org~trusty+1) ...\nSetting up libcroco3:amd64 (0.6.8-2ubuntu1) ...\nSetting up libunistring0:amd64 (0.9.3-5ubuntu3) ...\nSetting up libgettextpo0:amd64 (0.18.3.1-1ubuntu3) ...\nSetting up libpcrecpp0:amd64 (1:8.31-2ubuntu2.2) ...\nSetting up libxslt1.1:amd64 (1.1.28-2build1) ...\nSetting up libzip4:amd64 (1.1.1-1.1+deb.sury.org~trusty+2) ...\nSetting up libxmlrpc-epi0:amd64 (0.54.2-1ubuntu1) ...\nSetting up m4 (1.4.17-2ubuntu1) ...\nSetting up autoconf (2.69-6) ...\nSetting up autotools-dev (20130810.1) ...\nSetting up automake (1:1.14.1-2ubuntu1) ...\nupdate-alternatives: using /usr/bin/automake-1.14 to provide /usr/bin/automake (automake) in auto mode\nSetting up gettext (0.18.3.1-1ubuntu3) ...\nSetting up intltool-debian (0.35.0+20060710.1) ...\nSetting up po-debconf (1.0.16+nmu2ubuntu1) ...\nSetting up dh-apparmor (2.8.95~2430-0ubuntu5.3) ...\nSetting up debhelper (9.20131227ubuntu1) ...\nSetting up libasprintf-dev:amd64 (0.18.3.1-1ubuntu3) ...\nSetting up libgettextpo-dev:amd64 (0.18.3.1-1ubuntu3) ...\nSetting up liblist-moreutils-perl (0.33-1build3) ...\nSetting up libltdl-dev:amd64 (2.4.2-1.7ubuntu1) ...\nSetting up libsys-hostname-long-perl (1.4-3) ...\nSetting up libmail-sendmail-perl (0.79.16-1) ...\nSetting up libmcrypt4 (2.5.8-3.1ubuntu1) ...\nSetting up libpcre3-dev:amd64 (1:8.31-2ubuntu2.2) ...\nSetting up zlib1g-dev:amd64 (1:1.2.8.dfsg-1ubuntu1) ...\nSetting up libssl-dev:amd64 (1.0.2g-1+deb.sury.org~trusty+1) ...\nSetting up libssl-doc (1.0.2g-1+deb.sury.org~trusty+1) ...\nSetting up libtool (2.4.2-1.7ubuntu1) ...\nSetting up php-common (1:36+deb.sury.org~trusty+1) ...\nSetting up php7.0-common (7.0.5-1+deb.sury.org~trusty+1) ...\nSetting up php7.0-json (7.0.5-1+deb.sury.org~trusty+1) ...\nSetting up php7.0-opcache (7.0.5-1+deb.sury.org~trusty+1) ...\nSetting up php7.0-readline (7.0.5-1+deb.sury.org~trusty+1) ...\nSetting up php7.0-cli (7.0.5-1+deb.sury.org~trusty+1) ...\nupdate-alternatives: using /usr/bin/php7.0 to provide /usr/bin/php (php) in auto mode\nupdate-alternatives: using /usr/bin/phar7.0 to provide /usr/bin/phar (phar) in auto mode\nupdate-alternatives: using /usr/bin/phar.phar7.0 to provide /usr/bin/phar.phar (phar.phar) in auto mode\nSetting up php7.0-xml (7.0.5-1+deb.sury.org~trusty+1) ...\nSetting up php7.0-curl (7.0.5-1+deb.sury.org~trusty+1) ...\nSetting up shtool (2.0.8-6) ...\nSetting up php7.0-gd (7.0.5-1+deb.sury.org~trusty+1) ...\nSetting up php7.0-mbstring (7.0.5-1+deb.sury.org~trusty+1) ...\nSetting up php7.0-mcrypt (7.0.5-1+deb.sury.org~trusty+1) ...\nSetting up php7.0-mysql (7.0.5-1+deb.sury.org~trusty+1) ...\nSetting up php7.0-xmlrpc (7.0.5-1+deb.sury.org~trusty+1) ...\nSetting up php7.0-zip (7.0.5-1+deb.sury.org~trusty+1) ...\nSetting up dh-php (0.10+deb.sury.org~trusty+1) ...\nProcessing triggers for libc-bin (2.19-0ubuntu6.7) ...\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following extra packages will be installed:", "  autoconf automake autotools-dev debhelper dh-apparmor dh-php gettext", "  intltool-debian libasprintf-dev libcroco3 libgettextpo-dev libgettextpo0", "  liblist-moreutils-perl libltdl-dev libmail-sendmail-perl libmcrypt4 libpcre3", "  libpcre3-dev libpcrecpp0 libssl-dev libssl-doc libssl1.0.2", "  libsys-hostname-long-perl libtool libunistring0 libxmlrpc-epi0 libxslt1.1", "  libzip4 m4 php-common php-pear php7.0-json php7.0-readline pkg-php-tools", "  po-debconf shtool zlib1g-dev", "Suggested packages:", "  autoconf2.13 autoconf-archive gnu-standards autoconf-doc dh-make", "  apparmor-easyprof gettext-doc libtool-doc libmcrypt-dev mcrypt automaken", "  gfortran fortran95-compiler gcj-jdk libmail-box-perl", "The following NEW packages will be installed:", "  autoconf automake autotools-dev debhelper dh-apparmor dh-php gettext", "  intltool-debian libasprintf-dev libcroco3 libgettextpo-dev libgettextpo0", "  liblist-moreutils-perl libltdl-dev libmail-sendmail-perl libmcrypt4", "  libpcre3-dev libpcrecpp0 libssl-dev libssl-doc libssl1.0.2", "  libsys-hostname-long-perl libtool libunistring0 libxmlrpc-epi0 libxslt1.1", "  libzip4 m4 php-common php-pear php7.0-cli php7.0-common php7.0-curl", "  php7.0-dev php7.0-fpm php7.0-gd php7.0-json php7.0-mbstring php7.0-mcrypt", "  php7.0-mysql php7.0-opcache php7.0-readline php7.0-xml php7.0-xmlrpc", "  php7.0-zip pkg-php-tools po-debconf shtool zlib1g-dev", "The following packages will be upgraded:", "  libpcre3", "1 upgraded, 49 newly installed, 0 to remove and 27 not upgraded.", "Need to get 13.6 MB of archives.", "After this operation, 54.3 MB of additional disk space will be used.", "Get:1 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libpcre3 amd64 1:8.31-2ubuntu2.2 [144 kB]", "Get:2 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main libssl1.0.2 amd64 1.0.2g-1+deb.sury.org~trusty+1 [1261 kB]", "Get:3 http://archive.ubuntu.com/ubuntu/ trusty/main libcroco3 amd64 0.6.8-2ubuntu1 [82.4 kB]", "Get:4 http://archive.ubuntu.com/ubuntu/ trusty/main libunistring0 amd64 0.9.3-5ubuntu3 [271 kB]", "Get:5 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libgettextpo0 amd64 0.18.3.1-1ubuntu3 [108 kB]", "Get:6 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libpcrecpp0 amd64 1:8.31-2ubuntu2.2 [14.5 kB]", "Get:7 http://archive.ubuntu.com/ubuntu/ trusty/main libxslt1.1 amd64 1.1.28-2build1 [145 kB]", "Get:8 http://archive.ubuntu.com/ubuntu/ trusty/universe libxmlrpc-epi0 amd64 0.54.2-1ubuntu1 [30.0 kB]", "Get:9 http://archive.ubuntu.com/ubuntu/ trusty/main m4 amd64 1.4.17-2ubuntu1 [195 kB]", "Get:10 http://archive.ubuntu.com/ubuntu/ trusty/main autoconf all 2.69-6 [322 kB]", "Get:11 http://archive.ubuntu.com/ubuntu/ trusty/main autotools-dev all 20130810.1 [44.3 kB]", "Get:12 http://archive.ubuntu.com/ubuntu/ trusty/main automake all 1:1.14.1-2ubuntu1 [510 kB]", "Get:13 http://archive.ubuntu.com/ubuntu/ trusty-updates/main gettext amd64 0.18.3.1-1ubuntu3 [829 kB]", "Get:14 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main libzip4 amd64 1.1.1-1.1+deb.sury.org~trusty+2 [37.7 kB]", "Get:15 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main libssl-dev amd64 1.0.2g-1+deb.sury.org~trusty+1 [1528 kB]", "Get:16 http://archive.ubuntu.com/ubuntu/ trusty/main intltool-debian all 0.35.0+20060710.1 [31.6 kB]", "Get:17 http://archive.ubuntu.com/ubuntu/ trusty/main po-debconf all 1.0.16+nmu2ubuntu1 [210 kB]", "Get:18 http://archive.ubuntu.com/ubuntu/ trusty-updates/main dh-apparmor all 2.8.95~2430-0ubuntu5.3 [12.2 kB]", "Get:19 http://archive.ubuntu.com/ubuntu/ trusty/main debhelper all 9.20131227ubuntu1 [604 kB]", "Get:20 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libasprintf-dev amd64 0.18.3.1-1ubuntu3 [4438 B]", "Get:21 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libgettextpo-dev amd64 0.18.3.1-1ubuntu3 [122 kB]", "Get:22 http://archive.ubuntu.com/ubuntu/ trusty/main liblist-moreutils-perl amd64 0.33-1build3 [48.5 kB]", "Get:23 http://archive.ubuntu.com/ubuntu/ trusty/main libltdl-dev amd64 2.4.2-1.7ubuntu1 [157 kB]", "Get:24 http://archive.ubuntu.com/ubuntu/ trusty/main libsys-hostname-long-perl all 1.4-3 [11.3 kB]", "Get:25 http://archive.ubuntu.com/ubuntu/ trusty/main libmail-sendmail-perl all 0.79.16-1 [26.5 kB]", "Get:26 http://archive.ubuntu.com/ubuntu/ trusty/universe libmcrypt4 amd64 2.5.8-3.1ubuntu1 [61.9 kB]", "Get:27 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libpcre3-dev amd64 1:8.31-2ubuntu2.2 [237 kB]", "Get:28 http://archive.ubuntu.com/ubuntu/ trusty/main zlib1g-dev amd64 1:1.2.8.dfsg-1ubuntu1 [183 kB]", "Get:29 http://archive.ubuntu.com/ubuntu/ trusty/main libtool amd64 2.4.2-1.7ubuntu1 [188 kB]", "Get:30 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main libssl-doc all 1.0.2g-1+deb.sury.org~trusty+1 [1257 kB]", "Get:31 http://archive.ubuntu.com/ubuntu/ trusty/main shtool all 2.0.8-6 [149 kB]", "Get:32 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php-common all 1:36+deb.sury.org~trusty+1 [12.0 kB]", "Get:33 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-common amd64 7.0.5-1+deb.sury.org~trusty+1 [487 kB]", "Get:34 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-json amd64 7.0.5-1+deb.sury.org~trusty+1 [17.0 kB]", "Get:35 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-opcache amd64 7.0.5-1+deb.sury.org~trusty+1 [76.0 kB]", "Get:36 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-readline amd64 7.0.5-1+deb.sury.org~trusty+1 [12.2 kB]", "Get:37 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-cli amd64 7.0.5-1+deb.sury.org~trusty+1 [1248 kB]", "Get:38 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-xml amd64 7.0.5-1+deb.sury.org~trusty+1 [113 kB]", "Get:39 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php-pear all 1:1.10.1+submodules+notgz-6+deb.sury.org~trusty+1 [284 kB]", "Get:40 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-curl amd64 7.0.5-1+deb.sury.org~trusty+1 [26.9 kB]", "Get:41 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-dev amd64 7.0.5-1+deb.sury.org~trusty+1 [508 kB]", "Get:42 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-fpm amd64 7.0.5-1+deb.sury.org~trusty+1 [1254 kB]", "Get:43 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-gd amd64 7.0.5-1+deb.sury.org~trusty+1 [27.0 kB]", "Get:44 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-mbstring amd64 7.0.5-1+deb.sury.org~trusty+1 [462 kB]", "Get:45 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-mcrypt amd64 7.0.5-1+deb.sury.org~trusty+1 [14.5 kB]", "Get:46 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-mysql amd64 7.0.5-1+deb.sury.org~trusty+1 [123 kB]", "Get:47 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-xmlrpc amd64 7.0.5-1+deb.sury.org~trusty+1 [12.8 kB]", "Get:48 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0-zip amd64 7.0.5-1+deb.sury.org~trusty+1 [19.9 kB]", "Get:49 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main dh-php all 0.10+deb.sury.org~trusty+1 [7304 B]", "Get:50 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main pkg-php-tools all 1.32+deb.sury.org~trusty+1 [38.1 kB]", "Preconfiguring packages ...", "Fetched 13.6 MB in 16s (817 kB/s)", "(Reading database ... 65714 files and directories currently installed.)", "Preparing to unpack .../libpcre3_1%3a8.31-2ubuntu2.2_amd64.deb ...", "Unpacking libpcre3:amd64 (1:8.31-2ubuntu2.2) over (1:8.31-2ubuntu2.1) ...", "Processing triggers for man-db (2.6.7.1-1ubuntu1) ...", "Setting up libpcre3:amd64 (1:8.31-2ubuntu2.2) ...", "Processing triggers for libc-bin (2.19-0ubuntu6.7) ...", "Selecting previously unselected package libssl1.0.2:amd64.", "(Reading database ... 65714 files and directories currently installed.)", "Preparing to unpack .../libssl1.0.2_1.0.2g-1+deb.sury.org~trusty+1_amd64.deb ...", "Unpacking libssl1.0.2:amd64 (1.0.2g-1+deb.sury.org~trusty+1) ...", "Selecting previously unselected package libcroco3:amd64.", "Preparing to unpack .../libcroco3_0.6.8-2ubuntu1_amd64.deb ...", "Unpacking libcroco3:amd64 (0.6.8-2ubuntu1) ...", "Selecting previously unselected package libunistring0:amd64.", "Preparing to unpack .../libunistring0_0.9.3-5ubuntu3_amd64.deb ...", "Unpacking libunistring0:amd64 (0.9.3-5ubuntu3) ...", "Selecting previously unselected package libgettextpo0:amd64.", "Preparing to unpack .../libgettextpo0_0.18.3.1-1ubuntu3_amd64.deb ...", "Unpacking libgettextpo0:amd64 (0.18.3.1-1ubuntu3) ...", "Selecting previously unselected package libpcrecpp0:amd64.", "Preparing to unpack .../libpcrecpp0_1%3a8.31-2ubuntu2.2_amd64.deb ...", "Unpacking libpcrecpp0:amd64 (1:8.31-2ubuntu2.2) ...", "Selecting previously unselected package libxslt1.1:amd64.", "Preparing to unpack .../libxslt1.1_1.1.28-2build1_amd64.deb ...", "Unpacking libxslt1.1:amd64 (1.1.28-2build1) ...", "Selecting previously unselected package libzip4:amd64.", "Preparing to unpack .../libzip4_1.1.1-1.1+deb.sury.org~trusty+2_amd64.deb ...", "Unpacking libzip4:amd64 (1.1.1-1.1+deb.sury.org~trusty+2) ...", "Selecting previously unselected package libxmlrpc-epi0:amd64.", "Preparing to unpack .../libxmlrpc-epi0_0.54.2-1ubuntu1_amd64.deb ...", "Unpacking libxmlrpc-epi0:amd64 (0.54.2-1ubuntu1) ...", "Selecting previously unselected package m4.", "Preparing to unpack .../m4_1.4.17-2ubuntu1_amd64.deb ...", "Unpacking m4 (1.4.17-2ubuntu1) ...", "Selecting previously unselected package autoconf.", "Preparing to unpack .../autoconf_2.69-6_all.deb ...", "Unpacking autoconf (2.69-6) ...", "Selecting previously unselected package autotools-dev.", "Preparing to unpack .../autotools-dev_20130810.1_all.deb ...", "Unpacking autotools-dev (20130810.1) ...", "Selecting previously unselected package automake.", "Preparing to unpack .../automake_1%3a1.14.1-2ubuntu1_all.deb ...", "Unpacking automake (1:1.14.1-2ubuntu1) ...", "Selecting previously unselected package gettext.", "Preparing to unpack .../gettext_0.18.3.1-1ubuntu3_amd64.deb ...", "Unpacking gettext (0.18.3.1-1ubuntu3) ...", "Selecting previously unselected package intltool-debian.", "Preparing to unpack .../intltool-debian_0.35.0+20060710.1_all.deb ...", "Unpacking intltool-debian (0.35.0+20060710.1) ...", "Selecting previously unselected package po-debconf.", "Preparing to unpack .../po-debconf_1.0.16+nmu2ubuntu1_all.deb ...", "Unpacking po-debconf (1.0.16+nmu2ubuntu1) ...", "Selecting previously unselected package dh-apparmor.", "Preparing to unpack .../dh-apparmor_2.8.95~2430-0ubuntu5.3_all.deb ...", "Unpacking dh-apparmor (2.8.95~2430-0ubuntu5.3) ...", "Selecting previously unselected package debhelper.", "Preparing to unpack .../debhelper_9.20131227ubuntu1_all.deb ...", "Unpacking debhelper (9.20131227ubuntu1) ...", "Selecting previously unselected package libasprintf-dev:amd64.", "Preparing to unpack .../libasprintf-dev_0.18.3.1-1ubuntu3_amd64.deb ...", "Unpacking libasprintf-dev:amd64 (0.18.3.1-1ubuntu3) ...", "Selecting previously unselected package libgettextpo-dev:amd64.", "Preparing to unpack .../libgettextpo-dev_0.18.3.1-1ubuntu3_amd64.deb ...", "Unpacking libgettextpo-dev:amd64 (0.18.3.1-1ubuntu3) ...", "Selecting previously unselected package liblist-moreutils-perl.", "Preparing to unpack .../liblist-moreutils-perl_0.33-1build3_amd64.deb ...", "Unpacking liblist-moreutils-perl (0.33-1build3) ...", "Selecting previously unselected package libltdl-dev:amd64.", "Preparing to unpack .../libltdl-dev_2.4.2-1.7ubuntu1_amd64.deb ...", "Unpacking libltdl-dev:amd64 (2.4.2-1.7ubuntu1) ...", "Selecting previously unselected package libsys-hostname-long-perl.", "Preparing to unpack .../libsys-hostname-long-perl_1.4-3_all.deb ...", "Unpacking libsys-hostname-long-perl (1.4-3) ...", "Selecting previously unselected package libmail-sendmail-perl.", "Preparing to unpack .../libmail-sendmail-perl_0.79.16-1_all.deb ...", "Unpacking libmail-sendmail-perl (0.79.16-1) ...", "Selecting previously unselected package libmcrypt4.", "Preparing to unpack .../libmcrypt4_2.5.8-3.1ubuntu1_amd64.deb ...", "Unpacking libmcrypt4 (2.5.8-3.1ubuntu1) ...", "Selecting previously unselected package libpcre3-dev:amd64.", "Preparing to unpack .../libpcre3-dev_1%3a8.31-2ubuntu2.2_amd64.deb ...", "Unpacking libpcre3-dev:amd64 (1:8.31-2ubuntu2.2) ...", "Selecting previously unselected package zlib1g-dev:amd64.", "Preparing to unpack .../zlib1g-dev_1%3a1.2.8.dfsg-1ubuntu1_amd64.deb ...", "Unpacking zlib1g-dev:amd64 (1:1.2.8.dfsg-1ubuntu1) ...", "Selecting previously unselected package libssl-dev:amd64.", "Preparing to unpack .../libssl-dev_1.0.2g-1+deb.sury.org~trusty+1_amd64.deb ...", "Unpacking libssl-dev:amd64 (1.0.2g-1+deb.sury.org~trusty+1) ...", "Selecting previously unselected package libssl-doc.", "Preparing to unpack .../libssl-doc_1.0.2g-1+deb.sury.org~trusty+1_all.deb ...", "Unpacking libssl-doc (1.0.2g-1+deb.sury.org~trusty+1) ...", "Selecting previously unselected package libtool.", "Preparing to unpack .../libtool_2.4.2-1.7ubuntu1_amd64.deb ...", "Unpacking libtool (2.4.2-1.7ubuntu1) ...", "Selecting previously unselected package php-common.", "Preparing to unpack .../php-common_1%3a36+deb.sury.org~trusty+1_all.deb ...", "Unpacking php-common (1:36+deb.sury.org~trusty+1) ...", "Selecting previously unselected package php7.0-common.", "Preparing to unpack .../php7.0-common_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...", "Unpacking php7.0-common (7.0.5-1+deb.sury.org~trusty+1) ...", "Selecting previously unselected package php7.0-json.", "Preparing to unpack .../php7.0-json_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...", "Unpacking php7.0-json (7.0.5-1+deb.sury.org~trusty+1) ...", "Selecting previously unselected package php7.0-opcache.", "Preparing to unpack .../php7.0-opcache_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...", "Unpacking php7.0-opcache (7.0.5-1+deb.sury.org~trusty+1) ...", "Selecting previously unselected package php7.0-readline.", "Preparing to unpack .../php7.0-readline_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...", "Unpacking php7.0-readline (7.0.5-1+deb.sury.org~trusty+1) ...", "Selecting previously unselected package php7.0-cli.", "Preparing to unpack .../php7.0-cli_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...", "Unpacking php7.0-cli (7.0.5-1+deb.sury.org~trusty+1) ...", "Selecting previously unselected package php7.0-xml.", "Preparing to unpack .../php7.0-xml_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...", "Unpacking php7.0-xml (7.0.5-1+deb.sury.org~trusty+1) ...", "Selecting previously unselected package php-pear.", "Preparing to unpack .../php-pear_1%3a1.10.1+submodules+notgz-6+deb.sury.org~trusty+1_all.deb ...", "Unpacking php-pear (1:1.10.1+submodules+notgz-6+deb.sury.org~trusty+1) ...", "Selecting previously unselected package php7.0-curl.", "Preparing to unpack .../php7.0-curl_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...", "Unpacking php7.0-curl (7.0.5-1+deb.sury.org~trusty+1) ...", "Selecting previously unselected package shtool.", "Preparing to unpack .../shtool_2.0.8-6_all.deb ...", "Unpacking shtool (2.0.8-6) ...", "Selecting previously unselected package php7.0-dev.", "Preparing to unpack .../php7.0-dev_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...", "Unpacking php7.0-dev (7.0.5-1+deb.sury.org~trusty+1) ...", "Selecting previously unselected package php7.0-fpm.", "Preparing to unpack .../php7.0-fpm_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...", "Unpacking php7.0-fpm (7.0.5-1+deb.sury.org~trusty+1) ...", "Selecting previously unselected package php7.0-gd.", "Preparing to unpack .../php7.0-gd_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...", "Unpacking php7.0-gd (7.0.5-1+deb.sury.org~trusty+1) ...", "Selecting previously unselected package php7.0-mbstring.", "Preparing to unpack .../php7.0-mbstring_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...", "Unpacking php7.0-mbstring (7.0.5-1+deb.sury.org~trusty+1) ...", "Selecting previously unselected package php7.0-mcrypt.", "Preparing to unpack .../php7.0-mcrypt_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...", "Unpacking php7.0-mcrypt (7.0.5-1+deb.sury.org~trusty+1) ...", "Selecting previously unselected package php7.0-mysql.", "Preparing to unpack .../php7.0-mysql_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...", "Unpacking php7.0-mysql (7.0.5-1+deb.sury.org~trusty+1) ...", "Selecting previously unselected package php7.0-xmlrpc.", "Preparing to unpack .../php7.0-xmlrpc_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...", "Unpacking php7.0-xmlrpc (7.0.5-1+deb.sury.org~trusty+1) ...", "Selecting previously unselected package php7.0-zip.", "Preparing to unpack .../php7.0-zip_7.0.5-1+deb.sury.org~trusty+1_amd64.deb ...", "Unpacking php7.0-zip (7.0.5-1+deb.sury.org~trusty+1) ...", "Selecting previously unselected package dh-php.", "Preparing to unpack .../dh-php_0.10+deb.sury.org~trusty+1_all.deb ...", "Unpacking dh-php (0.10+deb.sury.org~trusty+1) ...", "Selecting previously unselected package pkg-php-tools.", "Preparing to unpack .../pkg-php-tools_1.32+deb.sury.org~trusty+1_all.deb ...", "Unpacking pkg-php-tools (1.32+deb.sury.org~trusty+1) ...", "Processing triggers for man-db (2.6.7.1-1ubuntu1) ...", "Processing triggers for install-info (5.2.0.dfsg.1-2) ...", "Processing triggers for ureadahead (0.100.0-16) ...", "Setting up libssl1.0.2:amd64 (1.0.2g-1+deb.sury.org~trusty+1) ...", "Setting up libcroco3:amd64 (0.6.8-2ubuntu1) ...", "Setting up libunistring0:amd64 (0.9.3-5ubuntu3) ...", "Setting up libgettextpo0:amd64 (0.18.3.1-1ubuntu3) ...", "Setting up libpcrecpp0:amd64 (1:8.31-2ubuntu2.2) ...", "Setting up libxslt1.1:amd64 (1.1.28-2build1) ...", "Setting up libzip4:amd64 (1.1.1-1.1+deb.sury.org~trusty+2) ...", "Setting up libxmlrpc-epi0:amd64 (0.54.2-1ubuntu1) ...", "Setting up m4 (1.4.17-2ubuntu1) ...", "Setting up autoconf (2.69-6) ...", "Setting up autotools-dev (20130810.1) ...", "Setting up automake (1:1.14.1-2ubuntu1) ...", "update-alternatives: using /usr/bin/automake-1.14 to provide /usr/bin/automake (automake) in auto mode", "Setting up gettext (0.18.3.1-1ubuntu3) ...", "Setting up intltool-debian (0.35.0+20060710.1) ...", "Setting up po-debconf (1.0.16+nmu2ubuntu1) ...", "Setting up dh-apparmor (2.8.95~2430-0ubuntu5.3) ...", "Setting up debhelper (9.20131227ubuntu1) ...", "Setting up libasprintf-dev:amd64 (0.18.3.1-1ubuntu3) ...", "Setting up libgettextpo-dev:amd64 (0.18.3.1-1ubuntu3) ...", "Setting up liblist-moreutils-perl (0.33-1build3) ...", "Setting up libltdl-dev:amd64 (2.4.2-1.7ubuntu1) ...", "Setting up libsys-hostname-long-perl (1.4-3) ...", "Setting up libmail-sendmail-perl (0.79.16-1) ...", "Setting up libmcrypt4 (2.5.8-3.1ubuntu1) ...", "Setting up libpcre3-dev:amd64 (1:8.31-2ubuntu2.2) ...", "Setting up zlib1g-dev:amd64 (1:1.2.8.dfsg-1ubuntu1) ...", "Setting up libssl-dev:amd64 (1.0.2g-1+deb.sury.org~trusty+1) ...", "Setting up libssl-doc (1.0.2g-1+deb.sury.org~trusty+1) ...", "Setting up libtool (2.4.2-1.7ubuntu1) ...", "Setting up php-common (1:36+deb.sury.org~trusty+1) ...", "Setting up php7.0-common (7.0.5-1+deb.sury.org~trusty+1) ...", "Setting up php7.0-json (7.0.5-1+deb.sury.org~trusty+1) ...", "Setting up php7.0-opcache (7.0.5-1+deb.sury.org~trusty+1) ...", "Setting up php7.0-readline (7.0.5-1+deb.sury.org~trusty+1) ...", "Setting up php7.0-cli (7.0.5-1+deb.sury.org~trusty+1) ...", "update-alternatives: using /usr/bin/php7.0 to provide /usr/bin/php (php) in auto mode", "update-alternatives: using /usr/bin/phar7.0 to provide /usr/bin/phar (phar) in auto mode", "update-alternatives: using /usr/bin/phar.phar7.0 to provide /usr/bin/phar.phar (phar.phar) in auto mode", "Setting up php7.0-xml (7.0.5-1+deb.sury.org~trusty+1) ...", "Setting up php7.0-curl (7.0.5-1+deb.sury.org~trusty+1) ...", "Setting up shtool (2.0.8-6) ...", "Setting up php7.0-gd (7.0.5-1+deb.sury.org~trusty+1) ...", "Setting up php7.0-mbstring (7.0.5-1+deb.sury.org~trusty+1) ...", "Setting up php7.0-mcrypt (7.0.5-1+deb.sury.org~trusty+1) ...", "Setting up php7.0-mysql (7.0.5-1+deb.sury.org~trusty+1) ...", "Setting up php7.0-xmlrpc (7.0.5-1+deb.sury.org~trusty+1) ...", "Setting up php7.0-zip (7.0.5-1+deb.sury.org~trusty+1) ...", "Setting up dh-php (0.10+deb.sury.org~trusty+1) ...", "Processing triggers for libc-bin (2.19-0ubuntu6.7) ..."]}
```

## Troubleshooting steps

I have done the following things to try and fix the issue:

Tried "vagrant up" again. No idea what the error means, so really have no idea what to try.

**Comment by austinpray** [comment]
Making issues like this should be against the law.

**Comment by reverbsoul** [comment]
Feel free to give me the proper way to create an issue and I'd be happy to do it.

**Comment by retlehs** [comment]
should be fixed soon: https://github.com/oerdnj/deb.sury.org/issues/315#issuecomment-204030883

**Comment by reverbsoul** [comment]
Great, thanks for being helpful @retlehs

**Comment by austinpray** [comment]
@reverbsoul I edited the original post and made a madlibs for you. Seems it's an upstream issue though

**Comment by reverbsoul** [comment]
Not sure how that's much more descriptive, and it seems like other people perfectly understood what I was asking for (including yourself). But, there it is. Thanks for the assistance in professionalizing my Issue!

**Comment by reverbsoul** [comment]
@retlehs That build went up, and I'm still getting the same error when I run 'vagrant up' - Is there perhaps a manual work-around to grab PHP7.0?

**Comment by reverbsoul** [comment]
Third time's the charm I guess. 'vagrant destroy' => 'vagrant up' installed PHP 7 with no issues, but get a new error on TASK [wordpress-setup : Create database of sites]

Error
```
fatal: [default]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute u'mysite.com'"}

But ultimately this is fixed, so I'm going to close the thread. Thanks for the help in figuring out the PHP 7 and making more accustomed to how I should be reporting issues in the future.
